### ISSUE TITLE
New release on crates.io

### ISSUE THREAD

**Issue by nishaq503** [cmccomb/rust-automl#2]
Hello,

I have found this crate useful in some of my research work.
I noticed that the last commit to this crate is about a year old but has not yet been published to crates.io.
Are there any blockers to publishing this?
If so, I would be interested in helping clear them?
If not, could you please release a new version on crates.io?

Thank you!

**Comment by cmccomb** [comment]
I'm so glad you're getting some use out of it! Would you mind sharing a bit more about what you use it for? 

Honestly, the biggest blocker has been a lack of time! I'll do a quick onceover and then push a new release to crates for you.

I would welcome your contributions to this project in the future. Here are a few things I've had in mind:
1. __Hyperparameter Tuning__ - I've been keeping an eye on some of the work in Smartcore that is establishing hyperparameter tuning capabilities. smartcorelib/smartcore#169
2. __Jank elimination__  - The current implementation is straight up bad (for some of the same reasons mentioned in that PR) and relies on serializing/deserializing models frequently. I'd love to find a better approach to that as well.

**Comment by nishaq503** [comment]
I'm using this crate for research in anomaly detection ([repo](https://github.com/URI-ABD/clam)). We had a python implementation some time ago and wanted to migrate to Rust.

In very broad strokes, we have a clustering algorithm and we train ML models on geometric properties of the clusters to select those clusters which would build a neighborhood graph which provides the best anomaly classification from a suite of anomaly detection algorithms.

I have forked this repo and will first take a look at jank elimination, before moving on to hyperparameter tuning.
